#spring.application.name=microservice-eureka
server:
  port: ${EUREKA_PORT}
spring:
  application:
    name: msvc-eureka
  config:
    import: optional:configserver:${CONFIG_SERVER_URL}
eureka:
  instance:
    hostname: ${HOSTNAME}
  client:
    register-with-eureka: false
    fetch-registry: false
  server-url:
    defaultZone: ${EUREKA_SERVER_URL}